# Privat — eigene Maschinen

Host nqpi-root
  HostName 192.168.178.159
  User root
  Port 22
  IdentityFile ~/.ssh/nqpi

Host nqpi-quentin
  HostName 192.168.178.159
  User quentin
  Port 22
  IdentityFile ~/.ssh/nqpi

Host quentins.dev
  HostName quentins.dev
  User root
  Port 22
  IdentityFile ~/.ssh/quentins.dev

Host nq-server
  HostName 192.168.178.157
  User root
  Port 22
  IdentityFile ~/.ssh/nq-server
