# Infrastruktur

Host infra-auth
  HostName 46.225.94.116
  User admin
  Port 222
  IdentityFile ~/.ssh/infrastructure

Host infra-business
  HostName 91.99.110.96
  User admin
  Port 222
  IdentityFile ~/.ssh/infrastructure

Host alte-infra
  HostName 23.88.78.96
  User root
  Port 22
  IdentityFile ~/.ssh/alteinfra

Host SST
  HostName 138.199.203.195
  User admin
  Port 22
  IdentityFile ~/.ssh/server-side-tracking
