# Kunden — alphabetisch

Host alpi-hetzner-live
  HostName dedi8111.your-server.de
  User alpirb
  Port 222
  IdentityFile ~/.ssh/alpi-timme

Host alpi-hetzner-stage
  HostName dedi8111.your-server.de
  User stagik
  Port 222
  IdentityFile ~/.ssh/alpi-timme

Host alpi-timme
  HostName k23n50.meinserver.io
  User c410744quenny
  Port 22
  IdentityFile ~/.ssh/alpi-timme

Host fairhandel-sw6
  HostName sw6.fair-handel-shop.de
  User sw6-fair
  Port 22
  IdentityFile ~/.ssh/sw6-fairhandel

Host franke-live
  HostName dedi4980.your-server.de
  User shopil
  Port 222
  IdentityFile ~/.ssh/franke-sw6

Host franke-stage
  HostName dedi4980.your-server.de
  User franke
  Port 222
  IdentityFile ~/.ssh/franke-sw6

Host kraft-baustoffe-main
  HostName srv-a-io.c-1175.maxcluster.net
  User web-user
  Port 22
  IdentityFile ~/.ssh/kraft-baustoffe

Host kraft-baustoffe-stage
  HostName dedi4980.your-server.de
  User krafti
  Port 222
  IdentityFile ~/.ssh/kraft-baustoffe

Host lexa
  HostName 62.113.230.87
  User web-user
  Port 22
  IdentityFile ~/.ssh/lexa

Host lupus
  HostName dedi7329.your-server.de
  User lupusu
  Port 222
  IdentityFile ~/.ssh/lupus

Host lutz-jesco
  HostName 167.235.120.226
  User lutzff
  Port 222
  IdentityFile ~/.ssh/lutz-jesco.shop

Host lutz-stage
  HostName 77.75.251.90
  User lutfrmsg
  Port 22
  IdentityFile ~/.ssh/lutz-stage

Host netbuddy
  HostName dedi4691.your-server.de
  User netbuddy
  Port 222
  IdentityFile ~/.ssh/netbuddy

Host netgrade-kas
  HostName w00e7898.kasserver.com
  User ssh-w00f1a0a
  Port 22
  IdentityFile ~/.ssh/kas-netgrade

Host netgrade-maxcluster
  HostName 109.71.74.124
  User web-user
  Port 22
  IdentityFile ~/.ssh/netgrade-maxcluster

Host piercingline_master
  HostName tun1.cluster.sc
  ForwardAgent yes
  User q.thees
  Port 15531
  IdentityFile ~/.ssh/piercingline

Host piercingline_stage66
  HostName tun1.cluster.sc
  ForwardAgent yes
  User q.thees
  Port 48748
  IdentityFile ~/.ssh/piercingline

Host rewe-dortmund
  HostName 188.245.111.194
  User rewedo
  Port 222
  IdentityFile ~/.ssh/rewe-dortmund

Host viertürme-sw6
  HostName sw6.vier-tuerme.de
  User sw6-abtei
  Port 22
  IdentityFile ~/.ssh/sw6-viertürme

Host zuessi-sw6
  HostName dedi4980.your-server.de
  User zuessi
  Port 222
  IdentityFile ~/.ssh/zuessi-sw6
